### ISSUE TITLE
Why use the word "to"?

### ISSUE THREAD

**Issue by richytong** [scopsy/await-to-js#26]
Scopsy, thank you for thinking about and productionizing something like this. I actually stumbled upon `await-to-js` when I was handling my own try/catch messiness with async/await. I too am a fan of the go way of handling errors (which might change in Go2 to my dismay). I just have one question and that is why use the word "to"? I understand that the module fundamentally uses the callback on a promise's `then` to nicely inline err and response, but how does "to" inform that procedure?

Thanks!

**Comment by mnlbox** [comment]
@scopsy  Please add this note to readme file :wink:
