### ISSUE TITLE
Q: Usage with AsyncIterators?

### ISSUE THREAD

**Issue by mattmeye** [scopsy/await-to-js#27]
Hello, 

first of all, thank you very much for your work. Await-to-js is very useful!

I have a question for usage of await-to-js with AsyncIterators:

```
# import { DataMapper } from "@aws/dynamodb-data-mapper";
for await (const foo of this.dataMapper.query(EntityModel, { ... })) {
    ...
}
```

It is possible to use 'to' also in this situation?

**Comment by ComBarnea** [comment]
@mattmeye sure thing, inside the for of use can use await-to-js just like any old await, sorry it took so long time to answer.
