### ISSUE TITLE
Idiomatic go-lang motivation is not readily avaible 

### ISSUE THREAD

**Issue by fdenzer** [scopsy/await-to-js#30]
I found this project via google,
but [blog.grossman.io](https://blog.grossman.io/how-to-write-async-await-without-try-catch-blocks-in-javascript/)
was not working, albeit the reasoning and comparison was a useful read.

While a cached version is available, I beg the author to move his intellectual
property this MIT licensed repository.

Aforementioned page [in google cache](https://webcache.googleusercontent.com/search?q=cache:pfWV2VXzXbQJ:https://blog.grossman.io/how-to-write-async-await-without-try-catch-blocks-in-javascript/)

**Comment by scopsy** [comment]
@fdenzer the blog is online again :)
