### ISSUE TITLE
ESLint prints a warning if error isn't used.

### ISSUE THREAD

**Issue by RomanChasovitin** [scopsy/await-to-js#36]
Hello everybody! I have a problem with your cool library.  When i wrap my Promise in the function, i need to get only response, without error. Like that:
`
const [_, res] = await to(
		this.rootStore.apiStore.request({
			url: URLS.SIGN_IN,
		}),
);
if (!res) return false;
`

But my ESLint prints a warning:
`
'_' is assigned a value but never used
`

I expect this error but I didn't understand how to properly handle it.
To improve this library, I'm ready to suggest you use Object as returned value instead of Array.
And I mean this should work like that:
`
const {
  error,
  data: response,
} = await to(fetch('some-api'));
` 

In this case, it will be possible to use one of the returned values without problems and also to save the ability to custom name variables.

I created PR about this issues - https://github.com/scopsy/await-to-js/pull/37

**Comment by scopsy** [comment]
@RomanChasovitin the idea behind using array destructuring vs using object destructuring was so that the consumer of the api can change the "error" name easily when having multiple `to` calls in a single scope. 

try @muffypl, closing this for now.
