### ISSUE TITLE
Does not work with Promise.promisify

### ISSUE THREAD

**Issue by jimfilippou** [scopsy/await-to-js#41]
Using 

- node v12.13.1
- yarn 1.19.2
- Windows 10

The following code should return `[undefined, [Object object]]`

```javascript
const Promise = require("bluebird");
const WebTorrent = require('webtorrent');

// Create the torrent client
const client = new WebTorrent();

// Make promises
client.addAsync = Promise.promisify(client.add);

const [err, data] = await to(client.addAsync(magnet, { path: pathToSave }));
```

In this example, err is the data i want, and data is undefined......

**Comment by JohnForster** [comment]
This is because webtorrent doesn't implement the nodejs callback api. Node.js callbacks should be in the form function(err, res), but the webtorrent callbacks are of the form function(res), and so Promisify interprets that first argument as an error.

**Comment by jimfilippou** [comment]
> This is because webtorrent doesn't implement the nodejs callback api. Node.js callbacks should be in the form function(err, res), but the webtorrent callbacks are of the form function(res), and so Promisify interprets that first argument as an error.

You are right
