### ISSUE TITLE
😎-er Name: await-try-catch

### ISSUE THREAD

**Issue by tylerbuchea** [scopsy/await-to-js#48]
I love this lib, but the name is just not as clean as the awesome functionality it provides.

So my proposed re-naming is "await-try-catch" and you could change the function from `to()` to `tc()` "tc" for try catch of course.

```js
import tc from "await-try-catch";

const [error, response] = await tc(fetch("/cool"));
```

It should make the use case more clear to newcomers and although this lib doesn't use a literal try-catch, this lib does replace the use of try-catch in your async code so it's related in that sense.

Most importantly I think naming can be important for adoption and I want everyone to use this so I stop having to deal with actual try-catch blocks or worse `.then` in other people's code.

What do you think? Give me some thumbs: 👍  or 👎

**Comment by scopsy** [comment]
Thanks for the suggestion @tylerbuchea , for now, I think we will stick with `await-to-js` since renaming an npm package is quite a thing if I remember correctly.

**Comment by tylerbuchea** [comment]
I forgot I posted this haha. That is a fair point, thanks for the reply scopsy. ❤️
