### ISSUE TITLE
Why try/catch blocks in async/await in the first place?

### ISSUE THREAD

**Issue by MaharishiCanada** [scopsy/await-to-js#5]
Instead of `try{ await promise } catch (e) {errorHandler(e)}` , we can do `await promise.catch(errorHandler)`. It's simpler and it uses the reject/resolve states mechanism of promises. Is there a use case where this would not work?

**Comment by MaharishiCanada** [comment]
I know this is not really an issue with the code. OTOH, if we can avoid try/catch blocks in a simpler way, we do not need a special app.

**Comment by rdsedmundo** [comment]
I think that the goal of the `try..catch` in this case, as is the `async/await`, is to make the code looks like synchronous.

If you add a callback like you've suggested, you would end in the same thing you had before using `await/async`.

**Comment by MaharishiCanada** [comment]
Why do you put callbacks to manage exceptions (i.e., exception handlers) and callbacks to define continuations in the same boat? Exceptions handling is most naturally taken care by exceptions handlers, i.e., by callbacks.  It avoids polluting the main flow with exceptions handling - it's good.   It will rarely, if ever, create a nested callbacks situation.  On the other hand, using callbacks to define continuations is what create a call backs hell.  So, we want to avoid continuation callbacks, but not necessarily exception callbacks. 

Moreover,  it's not true that async/await makes exception handlers obsolete.  The current idea with async/await is to use try/catch blocks for error handling.  So you define the error handlers into catch blocks. You don't really get rid of them - only define them differently with the extra cost over the catch method that you must explicitly add a try block. BTW, it feels more nested and cumbersome with try/catch blocks than with the catch method, but we are used to that. They are ugly, pollute the main flow, but we love our old good try/catch blocks.  I am not arguing against try/catch blocks.  I am just saying that with async/await we still use error handlers - either in catch blocks or in catch methods.

**Comment by MaharishiCanada** [comment]
Ok, perhaps we use the term "callback" when the handler is passed as an argument, which is not the case in a catch blocks, but it's a very superficial distinction. In both cases, you define an handler that gets called when an exception occurs. In fact, it's not too hard to define one as syntactic sugar over the other.

**Comment by MaharishiCanada** [comment]
My thoughts progressed since I wrote this comment. Now, my comments to your app  is that we do want to define exception handlers. Having the exception as a returned value forces you to handle the exception as if it was a part of the main flow, but this contradicts the fact that it is an exception.   Whether we define exception handlers in catch methods or in catch blocks is a different issue that is not directly related to your app.  Still, I want to point out that, on the contrary to what you say, using the catch method is similar to using a catch block: one can be defined as syntactic sugar over the other. Using the catch method is less cumbersome than using an extra try block over the entire function body, but I realize that this has not much to do with your app. Finally, why do you put exception handlers and continuation callbacks in the same boat?  Async/await is mostly used to get rid of the continuation callbacks - we still use exception handlers either in catch methods or in catch blocks.

**Comment by MaharishiCanada** [comment]
To extend on my comment to your app, I would say that the purpose of a catch is to manage the exception outside the main flow. One possible choice is to make the exception a returned value of the function that contains the catch block, thus delegating the management to the main flow, but it is rarely done.  Why one would want to do that? Instead, one would try to recover from the exception in the handler and, if possible, return a value that is useful in the main flow. Why polluting the main flow with exception handling?

**Comment by phra** [comment]
@MaharishiCanada imho it's handier to manage exception in the main flow because as @rdsedmundo said above you can choose to manage by yourself a failing promise instead of blow up everything. if i don't want to manage in that function i just throw the error (bubbling).
also in this way it's more explicit where a function can get an exception.

so usually my workflow is like this:

```javascript
import to from 'await-to-ts' // fork of mine with typescript types added
import { ifError } from 'assert' // assert library integrated in nodejs

async function main() {
  const [err, res] = await to(promise)
  ifError(err)
  ...
}

main()
```

the [ifError](https://nodejs.org/api/assert.html#assert_assert_iferror_value) let you to check if the error and throw it if it's defined so you can save yourself for typing everytime the `if + throw` block.

**Comment by MaharishiCanada** [comment]
@phra, well I don't understand why you find it handier to manage exceptions in the main flow.  I guess it can be a question of what you are used to.   So, it's good to have all these options, including an option that conveniently picks the option that you like for you, as in your case. This option was available in the handler, but the converse is not true. You can rethrow, but it will go to an handler at a higher level.

**Comment by phra** [comment]
@MaharishiCanada it's very simple. it's called [`let it crash` philosophy](https://stackoverflow.com/questions/4393197/erlangs-let-it-crash-philosophy-applicable-elsewhere). it's the opposite of defensive programming. it's a popular paradigm in erlang/elixir languages that are designed for a fail-safe environment.
in other words, it means that if there is something unexpected you will bubble the error up and eventually let the process crash in order to instantly spot the error and take actions accordingly.

**Comment by MaharishiCanada** [comment]
I will read this. I have no issue with different people liking different ways to handle exceptions. But, I do not understand how  handling exceptions in the main flow can make a big difference in terms of performance, etc.  My view is that you can do the exact same handling in an handler than you would in the main flow. It seems to me that the distinction is where the handling code shows up (in the main flow, in a catch method or in a catch block), not what the handling code can do and how efficiently it can do it.

**Comment by MaharishiCanada** [comment]
Of course, some times, you want to recover from the exception and return to the main flow, but that is the normal way to use an handler. My point is that I do not see what can be gained in terms of performance, etc. by doing every thing in the main flow and never using an handler.

**Comment by MaharishiCanada** [comment]
Ok, I just read your SO link. From what I read, it's a philosophy that applies when there is supervising context. So, you never handle errors and let a supervisor takes charge of them. In that context, handlers in the supervised code are not useful. However, in a way, the supervisor is like an exception handler separated from the main flow and we let every exception bubbles to that handler. I still don't see this as an argument in favor in handling errors in the main flow of the process that is being supervised.

**Comment by MaharishiCanada** [comment]
@phra, I kind of like the supervisor philosophy. The way I see it, you simply consider that there is no such a thing as an exception. What we call an exception, belongs in fact to the normal main flow of a supervisor. However, I think that to be useful, it has to be a built in part of the language. And, if one decides to implement that philosophy in Javascript, it should not be that every function that calls an async function becomes a supervisor.  The issue is that every async function is a kind of try/catch block. In most cases it should rethrow the exception. It should only return the exception to the main flow of the caller when this caller is the supervisor.

**Comment by MaharishiCanada** [comment]
Of course, one can push the philosophy so far as to consider that every function that calls an async function has to play the role of a supervisor !  It becomes a question of whether one is used to that strong philosophy.  It's a very restrictive philosophy, because you lose access to handlers and must  manage what we normally call exceptions in the main flow of the caller, but if one is used to that view point, why not.

**Comment by MaharishiCanada** [comment]
@phra, I read your snippet more carefully. You made it convenient to rethrow the error as a part of the main flow, if it is not to be managed there. So, it bubbles up until it reaches the supervisor. If it is a simple convenient rethrow, it does not disrupt that much the main flow and one can even argue that it's good to make it explicit in the main flow.  To sum up: the async/await construct eliminates the continuation callbacks but keeps the exception handlers (either in catch blocks or catch methods). The supervisor philosophy goes a step further and says that we should not even use exception handlers.

**Comment by MaharishiCanada** [comment]
I still don't get the "instantly" in what you wrote. The only difference is that you do the handling and re-throwing in the main flow. It's only a question of where the handling/re-throwing code shows up, not what it can do or how efficiently it can do it. There could be added efficiency, if the language is specially built for this philosophy, but your app over Javascript does not provide this efficiency.
