### ISSUE TITLE
如果想获取error里面的信息怎么办？

### ISSUE THREAD

**Issue by Lee66** [scopsy/await-to-js#53]
<img width="607" alt="image" src="https://user-images.githubusercontent.com/19661985/189264794-ad2d2905-270a-450e-abb9-df5a69872d2a.png">

**Comment by ghost** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
