### ISSUE TITLE
commonjs require

### ISSUE THREAD

**Issue by dkebler** [scopsy/await-to-js#8]
Using just nodejs 8.6   (not packed for browser nor using babel) 
after poking around in the dist folder I came up with this.

to = require('await-to-js').to

returns
```
function to(promise, errorExt) {
    return promise
        .then(function (data) { return [null, data]; })
        .catch(function (err) {
        if (errorExt) {
            Object.assign(err, errorExt);
        }
        return [err, undefined];
    });
}
```

so seems correct

You probably should put that in this readme as now nodejs supports async await natively, but still needs commonjs requires.

**Comment by DavidBernal** [comment]
https://github.com/scopsy/await-to-js/pull/6

¯\_(ツ)_/¯

**Comment by Munmw** [comment]
adding this line help: 

**var to = require('await-to-js').to;**

**Comment by simonepri** [comment]
Also this should work:
```js
const {to} = require('await-to-js');
```
